### ISSUE TITLE
Support string templates

### ISSUE THREAD

**Issue by cushon** [google/turbine#303]
See https://openjdk.org/jeps/430

String templates aren't compile-time constants, so they don't affect ABI. The fix should be to handle them during lexing and parsing so we can cleanly skip over the value of the template.

```
class T {
  void f(String name) {
    return STR."My name is \{name}";
  }
}
```

```
$ java -cp turbine-HEAD-SNAPSHOT-all-deps.jar com.google.turbine.main.Main --sources T.java --output /tmp/o.jar
...
T.java:3: error: unexpected input: {
    return STR."My name is \{name}";
                            ^
```

**Comment by vorburger** [comment]
@cushon are you (going to be) actively working on this? Or would you possibly welcome a contribution with a fix?

**Comment by vorburger** [comment]
@cushon close this? (Next step is https://github.com/bazelbuild/bazel/pull/21128.)
